### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by theoden8**
We have made some changes that need to be added to the `master` branch. Please, review the code and say if something bothers you.

### CODE REVIEW

**Review by mallok-s — COMMENTED** [review]
I would say this is fine to merge (there isn't much to say about the code. Since most of the issues have been picked up by previous reviews). Do you reckon we should wait for Jack to look over it? Or just merge?

**Comment by theoden8** [comment]
Yeah, I wanted Jack to look at it to make sure he is on the same page.

**Comment by jac32** [comment]
Hey guys, I'm going to take some time tonight an look this over thoroughly. I'm sure its fine, but it'd be good for me to get up to speed.

**Review by jac32 — COMMENTED** [review]
Looks good to me.
Just a couple of comments before merging:

It would be nice to have a requirements.txt file for using with virtual environments. I know there aren't many dependencies just now but will be useful going forward.

The general code quality seems quite nice and, at the function level, docs are great but we could do with comments/refactoring to clean up some of the larger functions. put_object in particular caught my eye.

There are a few places in the code using print statements to indicate progression through the code, it might be worthwhile switching in some more structured logging so this can be easily found and switched off when running.

Lastly, the variable names in some places are a little cryptic. I don't feel particularly strongly about the renaming of self to s as long as its consistent, but ppp = self.~~phyobjs~~objects looks quite strange to me. 


While it's outside the reach of this pull request, preconfiguration/loading of experiments is worth thinking about.

It's up to you guys if you'd rather make these change before merging or create new feature branches for stuff like logging. 

Let me know and I'll approve as appropriate.

**Review by jac32 — APPROVED** [review]
looks good, will merge in

**Pull request merged**
